[[navbar]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 10
    [[navbar]]
        identifier = "FicsIt-Networks"
        name = "FicsIt-Networks"
        url = "/docs/FicsIt-Networks/"
        weight = 10
        parent = "docs"
    [[navbar]]
        identifier = "Satisfactory"
        name = "Satisfactory"
        url = "/docs/Satisfactory/"
        weight = 20
        parent = "docs"
